/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.api;

import br.com.openpix.sdk.ApiException;
import br.com.openpix.sdk.model.ApiV1AccountAccountIdGet400Response;
import br.com.openpix.sdk.model.ApiV1ChargeIdRefundGet200Response;
import br.com.openpix.sdk.model.ApiV1ChargeIdRefundPost200Response;
import br.com.openpix.sdk.model.ChargeRefundPayload;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChargeRefundApi
 */
@Disabled
public class ChargeRefundApiTest {

    private final ChargeRefundApi api = new ChargeRefundApi();

    /**
     * Get all refunds of a charge
     *
     * Endpoint to get all refunds of a charge
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ChargeIdRefundGetTest() throws ApiException {
        String id = null;
        ApiV1ChargeIdRefundGet200Response response = api.apiV1ChargeIdRefundGet(id);
        // TODO: test validations
    }

    /**
     * Create a new refund for a charge
     *
     * Endpoint to create a new refund for a charge
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ChargeIdRefundPostTest() throws ApiException {
        String id = null;
        ChargeRefundPayload chargeRefundPayload = null;
        ApiV1ChargeIdRefundPost200Response response = api.apiV1ChargeIdRefundPost(id, chargeRefundPayload);
        // TODO: test validations
    }

}
