/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.api;

import br.com.openpix.sdk.ApiException;
import br.com.openpix.sdk.model.ApiV1AccountAccountIdGet400Response;
import br.com.openpix.sdk.model.ApiV1CustomerGet200Response;
import br.com.openpix.sdk.model.ApiV1CustomerIdGet200Response;
import br.com.openpix.sdk.model.ApiV1CustomerPost200Response;
import br.com.openpix.sdk.model.CustomerPayload;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerApi
 */
@Disabled
public class CustomerApiTest {

    private final CustomerApi api = new CustomerApi();

    /**
     * Get a list of customers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1CustomerGetTest() throws ApiException {
        ApiV1CustomerGet200Response response = api.apiV1CustomerGet();
        // TODO: test validations
    }

    /**
     * Get one customer
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1CustomerIdGetTest() throws ApiException {
        String id = null;
        ApiV1CustomerIdGet200Response response = api.apiV1CustomerIdGet(id);
        // TODO: test validations
    }

    /**
     * Create a new Customer
     *
     * Endpoint to create a new Customer
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1CustomerPostTest() throws ApiException {
        CustomerPayload customerPayload = null;
        ApiV1CustomerPost200Response response = api.apiV1CustomerPost(customerPayload);
        // TODO: test validations
    }

}
