/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.openpix.sdk.model.ApiV1WebhookPostRequestPixRaw;
import br.com.openpix.sdk.model.Charge;
import br.com.openpix.sdk.model.Customer;
import br.com.openpix.sdk.model.PixQrCode;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import br.com.openpix.sdk.JSON;

/**
 * ApiV1WebhookPostRequestPix
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-09T10:01:02.014525-03:00[America/Sao_Paulo]")
public class ApiV1WebhookPostRequestPix {
  public static final String SERIALIZED_NAME_PIX_QR_CODE = "pixQrCode";
  @SerializedName(SERIALIZED_NAME_PIX_QR_CODE)
  private PixQrCode pixQrCode;

  public static final String SERIALIZED_NAME_CHARGE = "charge";
  @SerializedName(SERIALIZED_NAME_CHARGE)
  private Charge charge;

  public static final String SERIALIZED_NAME_PAYER = "payer";
  @SerializedName(SERIALIZED_NAME_PAYER)
  private Customer payer;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private String time;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_TRANSACTION_I_D = "transactionID";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_I_D)
  private String transactionID;

  public static final String SERIALIZED_NAME_INFO_PAGADOR = "infoPagador";
  @SerializedName(SERIALIZED_NAME_INFO_PAGADOR)
  private String infoPagador;

  public static final String SERIALIZED_NAME_RAW = "raw";
  @SerializedName(SERIALIZED_NAME_RAW)
  private ApiV1WebhookPostRequestPixRaw raw;

  public ApiV1WebhookPostRequestPix() {
  }

  public ApiV1WebhookPostRequestPix pixQrCode(PixQrCode pixQrCode) {
    
    this.pixQrCode = pixQrCode;
    return this;
  }

   /**
   * Get pixQrCode
   * @return pixQrCode
  **/
  @javax.annotation.Nullable
  public PixQrCode getPixQrCode() {
    return pixQrCode;
  }


  public void setPixQrCode(PixQrCode pixQrCode) {
    this.pixQrCode = pixQrCode;
  }


  public ApiV1WebhookPostRequestPix charge(Charge charge) {
    
    this.charge = charge;
    return this;
  }

   /**
   * Get charge
   * @return charge
  **/
  @javax.annotation.Nullable
  public Charge getCharge() {
    return charge;
  }


  public void setCharge(Charge charge) {
    this.charge = charge;
  }


  public ApiV1WebhookPostRequestPix payer(Customer payer) {
    
    this.payer = payer;
    return this;
  }

   /**
   * Get payer
   * @return payer
  **/
  @javax.annotation.Nullable
  public Customer getPayer() {
    return payer;
  }


  public void setPayer(Customer payer) {
    this.payer = payer;
  }


  public ApiV1WebhookPostRequestPix time(String time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  public String getTime() {
    return time;
  }


  public void setTime(String time) {
    this.time = time;
  }


  public ApiV1WebhookPostRequestPix value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public ApiV1WebhookPostRequestPix transactionID(String transactionID) {
    
    this.transactionID = transactionID;
    return this;
  }

   /**
   * Get transactionID
   * @return transactionID
  **/
  @javax.annotation.Nullable
  public String getTransactionID() {
    return transactionID;
  }


  public void setTransactionID(String transactionID) {
    this.transactionID = transactionID;
  }


  public ApiV1WebhookPostRequestPix infoPagador(String infoPagador) {
    
    this.infoPagador = infoPagador;
    return this;
  }

   /**
   * Get infoPagador
   * @return infoPagador
  **/
  @javax.annotation.Nullable
  public String getInfoPagador() {
    return infoPagador;
  }


  public void setInfoPagador(String infoPagador) {
    this.infoPagador = infoPagador;
  }


  public ApiV1WebhookPostRequestPix raw(ApiV1WebhookPostRequestPixRaw raw) {
    
    this.raw = raw;
    return this;
  }

   /**
   * Get raw
   * @return raw
  **/
  @javax.annotation.Nullable
  public ApiV1WebhookPostRequestPixRaw getRaw() {
    return raw;
  }


  public void setRaw(ApiV1WebhookPostRequestPixRaw raw) {
    this.raw = raw;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV1WebhookPostRequestPix apiV1WebhookPostRequestPix = (ApiV1WebhookPostRequestPix) o;
    return Objects.equals(this.pixQrCode, apiV1WebhookPostRequestPix.pixQrCode) &&
        Objects.equals(this.charge, apiV1WebhookPostRequestPix.charge) &&
        Objects.equals(this.payer, apiV1WebhookPostRequestPix.payer) &&
        Objects.equals(this.time, apiV1WebhookPostRequestPix.time) &&
        Objects.equals(this.value, apiV1WebhookPostRequestPix.value) &&
        Objects.equals(this.transactionID, apiV1WebhookPostRequestPix.transactionID) &&
        Objects.equals(this.infoPagador, apiV1WebhookPostRequestPix.infoPagador) &&
        Objects.equals(this.raw, apiV1WebhookPostRequestPix.raw);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pixQrCode, charge, payer, time, value, transactionID, infoPagador, raw);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV1WebhookPostRequestPix {\n");
    sb.append("    pixQrCode: ").append(toIndentedString(pixQrCode)).append("\n");
    sb.append("    charge: ").append(toIndentedString(charge)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    transactionID: ").append(toIndentedString(transactionID)).append("\n");
    sb.append("    infoPagador: ").append(toIndentedString(infoPagador)).append("\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pixQrCode");
    openapiFields.add("charge");
    openapiFields.add("payer");
    openapiFields.add("time");
    openapiFields.add("value");
    openapiFields.add("transactionID");
    openapiFields.add("infoPagador");
    openapiFields.add("raw");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ApiV1WebhookPostRequestPix
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiV1WebhookPostRequestPix.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApiV1WebhookPostRequestPix is not found in the empty JSON string", ApiV1WebhookPostRequestPix.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ApiV1WebhookPostRequestPix.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApiV1WebhookPostRequestPix` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("time") != null && !jsonObj.get("time").isJsonNull()) && !jsonObj.get("time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
      if ((jsonObj.get("transactionID") != null && !jsonObj.get("transactionID").isJsonNull()) && !jsonObj.get("transactionID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionID").toString()));
      }
      if ((jsonObj.get("infoPagador") != null && !jsonObj.get("infoPagador").isJsonNull()) && !jsonObj.get("infoPagador").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `infoPagador` to be a primitive type in the JSON string but got `%s`", jsonObj.get("infoPagador").toString()));
      }
      // validate the optional field `raw`
      if (jsonObj.get("raw") != null && !jsonObj.get("raw").isJsonNull()) {
        ApiV1WebhookPostRequestPixRaw.validateJsonElement(jsonObj.get("raw"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiV1WebhookPostRequestPix.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiV1WebhookPostRequestPix' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiV1WebhookPostRequestPix> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiV1WebhookPostRequestPix.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiV1WebhookPostRequestPix>() {
           @Override
           public void write(JsonWriter out, ApiV1WebhookPostRequestPix value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiV1WebhookPostRequestPix read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApiV1WebhookPostRequestPix given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApiV1WebhookPostRequestPix
  * @throws IOException if the JSON string is invalid with respect to ApiV1WebhookPostRequestPix
  */
  public static ApiV1WebhookPostRequestPix fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiV1WebhookPostRequestPix.class);
  }

 /**
  * Convert an instance of ApiV1WebhookPostRequestPix to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

