/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.openpix.sdk.model.ApiV1CashbackFidelityPost201ResponseCashback;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import br.com.openpix.sdk.JSON;

/**
 * ApiV1CashbackFidelityPost201Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-09T10:01:02.014525-03:00[America/Sao_Paulo]")
public class ApiV1CashbackFidelityPost201Response {
  public static final String SERIALIZED_NAME_CASHBACK = "cashback";
  @SerializedName(SERIALIZED_NAME_CASHBACK)
  private ApiV1CashbackFidelityPost201ResponseCashback cashback;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public ApiV1CashbackFidelityPost201Response() {
  }

  public ApiV1CashbackFidelityPost201Response cashback(ApiV1CashbackFidelityPost201ResponseCashback cashback) {
    
    this.cashback = cashback;
    return this;
  }

   /**
   * Get cashback
   * @return cashback
  **/
  @javax.annotation.Nullable
  public ApiV1CashbackFidelityPost201ResponseCashback getCashback() {
    return cashback;
  }


  public void setCashback(ApiV1CashbackFidelityPost201ResponseCashback cashback) {
    this.cashback = cashback;
  }


  public ApiV1CashbackFidelityPost201Response message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * String explaining what happened
   * @return message
  **/
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV1CashbackFidelityPost201Response apiV1CashbackFidelityPost201Response = (ApiV1CashbackFidelityPost201Response) o;
    return Objects.equals(this.cashback, apiV1CashbackFidelityPost201Response.cashback) &&
        Objects.equals(this.message, apiV1CashbackFidelityPost201Response.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cashback, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV1CashbackFidelityPost201Response {\n");
    sb.append("    cashback: ").append(toIndentedString(cashback)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cashback");
    openapiFields.add("message");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ApiV1CashbackFidelityPost201Response
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiV1CashbackFidelityPost201Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApiV1CashbackFidelityPost201Response is not found in the empty JSON string", ApiV1CashbackFidelityPost201Response.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ApiV1CashbackFidelityPost201Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApiV1CashbackFidelityPost201Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `cashback`
      if (jsonObj.get("cashback") != null && !jsonObj.get("cashback").isJsonNull()) {
        ApiV1CashbackFidelityPost201ResponseCashback.validateJsonElement(jsonObj.get("cashback"));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiV1CashbackFidelityPost201Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiV1CashbackFidelityPost201Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiV1CashbackFidelityPost201Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiV1CashbackFidelityPost201Response.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiV1CashbackFidelityPost201Response>() {
           @Override
           public void write(JsonWriter out, ApiV1CashbackFidelityPost201Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiV1CashbackFidelityPost201Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApiV1CashbackFidelityPost201Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApiV1CashbackFidelityPost201Response
  * @throws IOException if the JSON string is invalid with respect to ApiV1CashbackFidelityPost201Response
  */
  public static ApiV1CashbackFidelityPost201Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiV1CashbackFidelityPost201Response.class);
  }

 /**
  * Convert an instance of ApiV1CashbackFidelityPost201Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

