/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.openpix.sdk.model.ChargeAdditionalInfoInner;
import br.com.openpix.sdk.model.Customer;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import br.com.openpix.sdk.JSON;

/**
 * Charge
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-09T10:01:02.014525-03:00[America/Sao_Paulo]")
public class Charge {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private BigDecimal value;

  public static final String SERIALIZED_NAME_CUSTOMER = "customer";
  @SerializedName(SERIALIZED_NAME_CUSTOMER)
  private Customer customer;

  /**
   * Charge type is used to determine whether a charge will have a deadline, fines and interests
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    DYNAMIC("DYNAMIC"),
    
    OVERDUE("OVERDUE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_BR_CODE = "brCode";
  @SerializedName(SERIALIZED_NAME_BR_CODE)
  private String brCode;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    COMPLETED("COMPLETED"),
    
    EXPIRED("EXPIRED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_CORRELATION_I_D = "correlationID";
  @SerializedName(SERIALIZED_NAME_CORRELATION_I_D)
  private String correlationID;

  public static final String SERIALIZED_NAME_PAYMENT_LINK_I_D = "paymentLinkID";
  @SerializedName(SERIALIZED_NAME_PAYMENT_LINK_I_D)
  private String paymentLinkID;

  public static final String SERIALIZED_NAME_PAYMENT_LINK_URL = "paymentLinkUrl";
  @SerializedName(SERIALIZED_NAME_PAYMENT_LINK_URL)
  private Object paymentLinkUrl = null;

  public static final String SERIALIZED_NAME_GLOBAL_I_D = "globalID";
  @SerializedName(SERIALIZED_NAME_GLOBAL_I_D)
  private Object globalID = null;

  public static final String SERIALIZED_NAME_TRANSACTION_I_D = "transactionID";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_I_D)
  private Object transactionID = null;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_QR_CODE_IMAGE = "qrCodeImage";
  @SerializedName(SERIALIZED_NAME_QR_CODE_IMAGE)
  private Object qrCodeImage = null;

  public static final String SERIALIZED_NAME_ADDITIONAL_INFO = "additionalInfo";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_INFO)
  private List<ChargeAdditionalInfoInner> additionalInfo;

  public static final String SERIALIZED_NAME_PIX_KEY = "pixKey";
  @SerializedName(SERIALIZED_NAME_PIX_KEY)
  private String pixKey;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_EXPIRES_IN = "expiresIn";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN)
  private String expiresIn;

  public Charge() {
  }

  public Charge value(BigDecimal value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  public BigDecimal getValue() {
    return value;
  }


  public void setValue(BigDecimal value) {
    this.value = value;
  }


  public Charge customer(Customer customer) {
    
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @javax.annotation.Nullable
  public Customer getCustomer() {
    return customer;
  }


  public void setCustomer(Customer customer) {
    this.customer = customer;
  }


  public Charge type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Charge type is used to determine whether a charge will have a deadline, fines and interests
   * @return type
  **/
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public Charge comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }


  public Charge brCode(String brCode) {
    
    this.brCode = brCode;
    return this;
  }

   /**
   * EMV BRCode to be rendered as a QRCode
   * @return brCode
  **/
  @javax.annotation.Nullable
  public String getBrCode() {
    return brCode;
  }


  public void setBrCode(String brCode) {
    this.brCode = brCode;
  }


  public Charge status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public Charge correlationID(String correlationID) {
    
    this.correlationID = correlationID;
    return this;
  }

   /**
   * Your correlation ID to keep track of this charge
   * @return correlationID
  **/
  @javax.annotation.Nullable
  public String getCorrelationID() {
    return correlationID;
  }


  public void setCorrelationID(String correlationID) {
    this.correlationID = correlationID;
  }


  public Charge paymentLinkID(String paymentLinkID) {
    
    this.paymentLinkID = paymentLinkID;
    return this;
  }

   /**
   * Payment Link ID, used on payment link and to retrieve qrcode image
   * @return paymentLinkID
  **/
  @javax.annotation.Nullable
  public String getPaymentLinkID() {
    return paymentLinkID;
  }


  public void setPaymentLinkID(String paymentLinkID) {
    this.paymentLinkID = paymentLinkID;
  }


  public Charge paymentLinkUrl(Object paymentLinkUrl) {
    
    this.paymentLinkUrl = paymentLinkUrl;
    return this;
  }

   /**
   * Payment Link URL to be shared with customers
   * @return paymentLinkUrl
  **/
  @javax.annotation.Nullable
  public Object getPaymentLinkUrl() {
    return paymentLinkUrl;
  }


  public void setPaymentLinkUrl(Object paymentLinkUrl) {
    this.paymentLinkUrl = paymentLinkUrl;
  }


  public Charge globalID(Object globalID) {
    
    this.globalID = globalID;
    return this;
  }

   /**
   * External ID of this charge
   * @return globalID
  **/
  @javax.annotation.Nullable
  public Object getGlobalID() {
    return globalID;
  }


  public void setGlobalID(Object globalID) {
    this.globalID = globalID;
  }


  public Charge transactionID(Object transactionID) {
    
    this.transactionID = transactionID;
    return this;
  }

   /**
   * unique uuid used as the txid from Pix into the provider from your openpix account. This field link the charge with the transaction when paid.
   * @return transactionID
  **/
  @javax.annotation.Nullable
  public Object getTransactionID() {
    return transactionID;
  }


  public void setTransactionID(Object transactionID) {
    this.transactionID = transactionID;
  }


  public Charge identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Custom identifier for EMV
   * @return identifier
  **/
  @javax.annotation.Nullable
  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public Charge qrCodeImage(Object qrCodeImage) {
    
    this.qrCodeImage = qrCodeImage;
    return this;
  }

   /**
   * QRCode image link URL
   * @return qrCodeImage
  **/
  @javax.annotation.Nullable
  public Object getQrCodeImage() {
    return qrCodeImage;
  }


  public void setQrCodeImage(Object qrCodeImage) {
    this.qrCodeImage = qrCodeImage;
  }


  public Charge additionalInfo(List<ChargeAdditionalInfoInner> additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  public Charge addAdditionalInfoItem(ChargeAdditionalInfoInner additionalInfoItem) {
    if (this.additionalInfo == null) {
      this.additionalInfo = new ArrayList<>();
    }
    this.additionalInfo.add(additionalInfoItem);
    return this;
  }

   /**
   * Additional info of the charge
   * @return additionalInfo
  **/
  @javax.annotation.Nullable
  public List<ChargeAdditionalInfoInner> getAdditionalInfo() {
    return additionalInfo;
  }


  public void setAdditionalInfo(List<ChargeAdditionalInfoInner> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }


  public Charge pixKey(String pixKey) {
    
    this.pixKey = pixKey;
    return this;
  }

   /**
   * Get pixKey
   * @return pixKey
  **/
  @javax.annotation.Nullable
  public String getPixKey() {
    return pixKey;
  }


  public void setPixKey(String pixKey) {
    this.pixKey = pixKey;
  }


  public Charge createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public Charge updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Charge expiresIn(String expiresIn) {
    
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * Get expiresIn
   * @return expiresIn
  **/
  @javax.annotation.Nullable
  public String getExpiresIn() {
    return expiresIn;
  }


  public void setExpiresIn(String expiresIn) {
    this.expiresIn = expiresIn;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Charge charge = (Charge) o;
    return Objects.equals(this.value, charge.value) &&
        Objects.equals(this.customer, charge.customer) &&
        Objects.equals(this.type, charge.type) &&
        Objects.equals(this.comment, charge.comment) &&
        Objects.equals(this.brCode, charge.brCode) &&
        Objects.equals(this.status, charge.status) &&
        Objects.equals(this.correlationID, charge.correlationID) &&
        Objects.equals(this.paymentLinkID, charge.paymentLinkID) &&
        Objects.equals(this.paymentLinkUrl, charge.paymentLinkUrl) &&
        Objects.equals(this.globalID, charge.globalID) &&
        Objects.equals(this.transactionID, charge.transactionID) &&
        Objects.equals(this.identifier, charge.identifier) &&
        Objects.equals(this.qrCodeImage, charge.qrCodeImage) &&
        Objects.equals(this.additionalInfo, charge.additionalInfo) &&
        Objects.equals(this.pixKey, charge.pixKey) &&
        Objects.equals(this.createdAt, charge.createdAt) &&
        Objects.equals(this.updatedAt, charge.updatedAt) &&
        Objects.equals(this.expiresIn, charge.expiresIn);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, customer, type, comment, brCode, status, correlationID, paymentLinkID, paymentLinkUrl, globalID, transactionID, identifier, qrCodeImage, additionalInfo, pixKey, createdAt, updatedAt, expiresIn);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Charge {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    brCode: ").append(toIndentedString(brCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    correlationID: ").append(toIndentedString(correlationID)).append("\n");
    sb.append("    paymentLinkID: ").append(toIndentedString(paymentLinkID)).append("\n");
    sb.append("    paymentLinkUrl: ").append(toIndentedString(paymentLinkUrl)).append("\n");
    sb.append("    globalID: ").append(toIndentedString(globalID)).append("\n");
    sb.append("    transactionID: ").append(toIndentedString(transactionID)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    qrCodeImage: ").append(toIndentedString(qrCodeImage)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    pixKey: ").append(toIndentedString(pixKey)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("value");
    openapiFields.add("customer");
    openapiFields.add("type");
    openapiFields.add("comment");
    openapiFields.add("brCode");
    openapiFields.add("status");
    openapiFields.add("correlationID");
    openapiFields.add("paymentLinkID");
    openapiFields.add("paymentLinkUrl");
    openapiFields.add("globalID");
    openapiFields.add("transactionID");
    openapiFields.add("identifier");
    openapiFields.add("qrCodeImage");
    openapiFields.add("additionalInfo");
    openapiFields.add("pixKey");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("expiresIn");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Charge
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Charge.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Charge is not found in the empty JSON string", Charge.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Charge.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Charge` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if ((jsonObj.get("brCode") != null && !jsonObj.get("brCode").isJsonNull()) && !jsonObj.get("brCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brCode").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("correlationID") != null && !jsonObj.get("correlationID").isJsonNull()) && !jsonObj.get("correlationID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `correlationID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("correlationID").toString()));
      }
      if ((jsonObj.get("paymentLinkID") != null && !jsonObj.get("paymentLinkID").isJsonNull()) && !jsonObj.get("paymentLinkID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentLinkID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentLinkID").toString()));
      }
      if ((jsonObj.get("identifier") != null && !jsonObj.get("identifier").isJsonNull()) && !jsonObj.get("identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identifier").toString()));
      }
      if (jsonObj.get("additionalInfo") != null && !jsonObj.get("additionalInfo").isJsonNull()) {
        JsonArray jsonArrayadditionalInfo = jsonObj.getAsJsonArray("additionalInfo");
        if (jsonArrayadditionalInfo != null) {
          // ensure the json data is an array
          if (!jsonObj.get("additionalInfo").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `additionalInfo` to be an array in the JSON string but got `%s`", jsonObj.get("additionalInfo").toString()));
          }

          // validate the optional field `additionalInfo` (array)
          for (int i = 0; i < jsonArrayadditionalInfo.size(); i++) {
            ChargeAdditionalInfoInner.validateJsonElement(jsonArrayadditionalInfo.get(i));
          };
        }
      }
      if ((jsonObj.get("pixKey") != null && !jsonObj.get("pixKey").isJsonNull()) && !jsonObj.get("pixKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pixKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pixKey").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull()) && !jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if ((jsonObj.get("expiresIn") != null && !jsonObj.get("expiresIn").isJsonNull()) && !jsonObj.get("expiresIn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiresIn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiresIn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Charge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Charge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Charge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Charge.class));

       return (TypeAdapter<T>) new TypeAdapter<Charge>() {
           @Override
           public void write(JsonWriter out, Charge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Charge read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Charge given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Charge
  * @throws IOException if the JSON string is invalid with respect to Charge
  */
  public static Charge fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Charge.class);
  }

 /**
  * Convert an instance of Charge to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

