/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.openpix.sdk.model.PreRegistrationObject;
import br.com.openpix.sdk.model.PreRegistrationUserObject;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import br.com.openpix.sdk.JSON;

/**
 * PreRegistrationPayloadObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-09T10:01:02.014525-03:00[America/Sao_Paulo]")
public class PreRegistrationPayloadObject {
  public static final String SERIALIZED_NAME_PRE_REGISTRATION = "preRegistration";
  @SerializedName(SERIALIZED_NAME_PRE_REGISTRATION)
  private PreRegistrationObject preRegistration;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private PreRegistrationUserObject user;

  public PreRegistrationPayloadObject() {
  }

  public PreRegistrationPayloadObject preRegistration(PreRegistrationObject preRegistration) {
    
    this.preRegistration = preRegistration;
    return this;
  }

   /**
   * Get preRegistration
   * @return preRegistration
  **/
  @javax.annotation.Nullable
  public PreRegistrationObject getPreRegistration() {
    return preRegistration;
  }


  public void setPreRegistration(PreRegistrationObject preRegistration) {
    this.preRegistration = preRegistration;
  }


  public PreRegistrationPayloadObject user(PreRegistrationUserObject user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  public PreRegistrationUserObject getUser() {
    return user;
  }


  public void setUser(PreRegistrationUserObject user) {
    this.user = user;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreRegistrationPayloadObject preRegistrationPayloadObject = (PreRegistrationPayloadObject) o;
    return Objects.equals(this.preRegistration, preRegistrationPayloadObject.preRegistration) &&
        Objects.equals(this.user, preRegistrationPayloadObject.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preRegistration, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreRegistrationPayloadObject {\n");
    sb.append("    preRegistration: ").append(toIndentedString(preRegistration)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("preRegistration");
    openapiFields.add("user");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PreRegistrationPayloadObject
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PreRegistrationPayloadObject.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PreRegistrationPayloadObject is not found in the empty JSON string", PreRegistrationPayloadObject.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PreRegistrationPayloadObject.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PreRegistrationPayloadObject` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `preRegistration`
      if (jsonObj.get("preRegistration") != null && !jsonObj.get("preRegistration").isJsonNull()) {
        PreRegistrationObject.validateJsonElement(jsonObj.get("preRegistration"));
      }
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        PreRegistrationUserObject.validateJsonElement(jsonObj.get("user"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PreRegistrationPayloadObject.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PreRegistrationPayloadObject' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PreRegistrationPayloadObject> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PreRegistrationPayloadObject.class));

       return (TypeAdapter<T>) new TypeAdapter<PreRegistrationPayloadObject>() {
           @Override
           public void write(JsonWriter out, PreRegistrationPayloadObject value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PreRegistrationPayloadObject read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PreRegistrationPayloadObject given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PreRegistrationPayloadObject
  * @throws IOException if the JSON string is invalid with respect to PreRegistrationPayloadObject
  */
  public static PreRegistrationPayloadObject fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PreRegistrationPayloadObject.class);
  }

 /**
  * Convert an instance of PreRegistrationPayloadObject to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

