/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiV1ChargeGet200ResponsePageInfoErrorsInnerData
 */
public class ApiV1ChargeGet200ResponsePageInfoErrorsInnerDataTest {
    private final ApiV1ChargeGet200ResponsePageInfoErrorsInnerData model = new ApiV1ChargeGet200ResponsePageInfoErrorsInnerData();

    /**
     * Model tests for ApiV1ChargeGet200ResponsePageInfoErrorsInnerData
     */
    @Test
    public void testApiV1ChargeGet200ResponsePageInfoErrorsInnerData() {
        // TODO: test ApiV1ChargeGet200ResponsePageInfoErrorsInnerData
    }

    /**
     * Test the property 'skip'
     */
    @Test
    public void skipTest() {
        // TODO: test skip
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

}
