/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiV1WebhookPostRequestPixRaw
 */
public class ApiV1WebhookPostRequestPixRawTest {
    private final ApiV1WebhookPostRequestPixRaw model = new ApiV1WebhookPostRequestPixRaw();

    /**
     * Model tests for ApiV1WebhookPostRequestPixRaw
     */
    @Test
    public void testApiV1WebhookPostRequestPixRaw() {
        // TODO: test ApiV1WebhookPostRequestPixRaw
    }

    /**
     * Test the property 'endToEndId'
     */
    @Test
    public void endToEndIdTest() {
        // TODO: test endToEndId
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'valor'
     */
    @Test
    public void valorTest() {
        // TODO: test valor
    }

    /**
     * Test the property 'horario'
     */
    @Test
    public void horarioTest() {
        // TODO: test horario
    }

    /**
     * Test the property 'infoPagador'
     */
    @Test
    public void infoPagadorTest() {
        // TODO: test infoPagador
    }

}
