/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import br.com.openpix.sdk.model.ApiV1WebhookPostRequestPixRaw;
import br.com.openpix.sdk.model.Charge;
import br.com.openpix.sdk.model.Customer;
import br.com.openpix.sdk.model.PixQrCode;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiV1WebhookPostRequestPix
 */
public class ApiV1WebhookPostRequestPixTest {
    private final ApiV1WebhookPostRequestPix model = new ApiV1WebhookPostRequestPix();

    /**
     * Model tests for ApiV1WebhookPostRequestPix
     */
    @Test
    public void testApiV1WebhookPostRequestPix() {
        // TODO: test ApiV1WebhookPostRequestPix
    }

    /**
     * Test the property 'pixQrCode'
     */
    @Test
    public void pixQrCodeTest() {
        // TODO: test pixQrCode
    }

    /**
     * Test the property 'charge'
     */
    @Test
    public void chargeTest() {
        // TODO: test charge
    }

    /**
     * Test the property 'payer'
     */
    @Test
    public void payerTest() {
        // TODO: test payer
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'transactionID'
     */
    @Test
    public void transactionIDTest() {
        // TODO: test transactionID
    }

    /**
     * Test the property 'infoPagador'
     */
    @Test
    public void infoPagadorTest() {
        // TODO: test infoPagador
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

}
