/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import br.com.openpix.sdk.model.ChargeAdditionalInfoInner;
import br.com.openpix.sdk.model.ChargePayloadFines;
import br.com.openpix.sdk.model.ChargePayloadInterests;
import br.com.openpix.sdk.model.CustomerPayload;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChargePayload
 */
public class ChargePayloadTest {
    private final ChargePayload model = new ChargePayload();

    /**
     * Model tests for ChargePayload
     */
    @Test
    public void testChargePayload() {
        // TODO: test ChargePayload
    }

    /**
     * Test the property 'correlationID'
     */
    @Test
    public void correlationIDTest() {
        // TODO: test correlationID
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'daysForDueDate'
     */
    @Test
    public void daysForDueDateTest() {
        // TODO: test daysForDueDate
    }

    /**
     * Test the property 'daysAfterDueDate'
     */
    @Test
    public void daysAfterDueDateTest() {
        // TODO: test daysAfterDueDate
    }

    /**
     * Test the property 'interests'
     */
    @Test
    public void interestsTest() {
        // TODO: test interests
    }

    /**
     * Test the property 'fines'
     */
    @Test
    public void finesTest() {
        // TODO: test fines
    }

    /**
     * Test the property 'additionalInfo'
     */
    @Test
    public void additionalInfoTest() {
        // TODO: test additionalInfo
    }

}
