/*
 * Woovi
 * A Woovi é uma Plataforma de Gestão de Pagamentos. Para utilizar nossa API você deve acessar  __[https://api.woovi.com/](https://api.woovi.com/)__ e somente o mesmo. A Woovi não aceita subdominios para a API.  Veja como configurar seu acesso a nossa API [aqui](https://developers.woovi.com/docs/apis/api-getting-started).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.openpix.sdk.model;

import br.com.openpix.sdk.model.PreRegistrationObject;
import br.com.openpix.sdk.model.PreRegistrationUserObject;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PreRegistrationPayloadObject
 */
public class PreRegistrationPayloadObjectTest {
    private final PreRegistrationPayloadObject model = new PreRegistrationPayloadObject();

    /**
     * Model tests for PreRegistrationPayloadObject
     */
    @Test
    public void testPreRegistrationPayloadObject() {
        // TODO: test PreRegistrationPayloadObject
    }

    /**
     * Test the property 'preRegistration'
     */
    @Test
    public void preRegistrationTest() {
        // TODO: test preRegistration
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
